import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { createServer } from 'node:net';
import { request as httpRequest } from 'node:http';
import { mkdtemp, mkdir } from 'node:fs/promises';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { MemoryStore } from '../src/memory-store.mjs';
import { EffectStore } from '../src/effect-store.mjs';

// Chromium normalizes trailing fractional zeroes and zero seconds on datetime-local inputs.
const browserDate = time => new Date(time).toISOString().replace(/\.000Z$/, 'Z').replace(/(\.\d*?[1-9])0+Z$/, '$1Z').replace(/:00Z$/, 'Z').replace(/Z$/, '');

test('structured memory queries show provenance, graph relations, temporal snapshots and exact JSON downloads', { timeout: 90000 }, async t => {
  const f = await fixture(t);
  const { sessionId } = await f.ok('create-session', { workspaceRoot: f.workspace });
  await f.ok('configure', { sessionId, expectedVersion: 0, input: { enabled: true, projectId: 'query-test', agentId: sessionId, workspaceRoot: f.workspace, sandbox: null, budgetTokens: 4000, anchors: [] } });
  const first = await f.ok('put-memory', { sessionId, reason: 'Reviewed task evidence', record: { kind: 'semantic', visibility: 'private', summary: 'Animation contract', validTime: 1000,
    content: { nodes: [{ id: 'task', type: 'task', label: 'Logo task' }, { id: 'file', type: 'artifact', label: '<img src=x onerror=alert(1)>' }], edges: [{ from: 'task', relation: 'produces', to: 'file' }] } } });
  await f.ok('put-memory', { sessionId, reason: 'Reviewed new revision', record: { id: first.id, expectedVersion: 1, kind: 'semantic', visibility: 'private', summary: 'Revised animation contract', validTime: 2000,
    content: { nodes: [{ id: 'task', type: 'task', label: 'Revised logo task' }, { id: 'file', type: 'artifact', label: 'animation.html' }], edges: [{ from: 'task', relation: 'produces', to: 'file' }] } } });
  await f.ok('put-memory', { sessionId, reason: 'Observed failure', record: { kind: 'procedural', visibility: 'private', summary: 'Verify artifacts', content: { rules: ['Check the output file'], applicability: { task: 'html' } } } });
  const { chromium } = await import('playwright-core');
  const browser = await chromium.launchPersistentContext(join(f.root, 'structured-browser'), { headless: true, executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', viewport: { width: 1440, height: 1000 } });
  t.after(() => browser.close());
  const page = await browser.newPage(); page.setDefaultTimeout(6000);
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(`${f.url}/memory-recovery?sessionId=${sessionId}`);
  await page.getByRole('tab', { name: '三类记忆', exact: true }).waitFor();
  await page.locator('#records').getByRole('button', { name: '查看详情' }).first().click();
  await page.locator('#detail').getByText('episodic', { exact: true }).waitFor();
  await page.locator('#kind').selectOption('semantic'); await page.locator('#list').click();
  await page.locator('#records').getByText('Revised animation contract', { exact: true }).waitFor();
  assert.match(await page.locator('#records').innerText(), /v2/);
  await page.locator('#records').getByRole('button', { name: '查看详情' }).click();
  await page.locator('#detail').getByText('Reviewed new revision', { exact: true }).waitFor();
  const downloadJSON = async id => {
    const pending = page.waitForEvent('download'); await page.locator(id).click();
    const download = await pending; assert.match(download.suggestedFilename(), /\.json$/);
    const stream = await download.createReadStream(); const chunks = []; for await (const chunk of stream) chunks.push(chunk);
    return JSON.parse(Buffer.concat(chunks).toString());
  };
  assert.equal((await downloadJSON('#download-detail')).data.id, first.id);
  await page.getByText('工作集分页 / 调入与调出', { exact: true }).click();
  await page.locator('#max-chars').fill('20'); await page.locator('#page-in').click();
  await page.waitForFunction(() => document.querySelector('#feedback').textContent !== '处理中…');
  assert.equal(await page.locator('#download-detail').isDisabled(), true, 'a partial working-set page is not a complete memory record');
  await page.locator('#page-out').click();
  await page.waitForFunction(() => document.querySelector('#feedback').textContent !== '处理中…');
  assert.equal(await page.locator('#download-detail').isDisabled(), true, 'an unpin receipt is not a memory record');
  const listed = await downloadJSON('#download-records');
  assert.equal(listed.sessionId, sessionId); assert.equal(listed.data.length, 1); assert.equal(listed.data[0].version, 2);
  await page.locator('#query').fill(''); await page.locator('#search').click();
  await page.waitForFunction(() => document.querySelector('#feedback').textContent !== '处理中…');
  assert.equal(await page.locator('#error').innerText(), '', 'empty search should list the selected category');
  await page.locator('#query').fill('does-not-exist-734'); await page.locator('#search').click();
  await page.locator('#records').getByText(/当前类别没有匹配记录/).waitFor();
  assert.equal((await downloadJSON('#download-records')).data.length, 0);
  await page.locator('#query').fill('Revised animation'); await page.locator('#search').click();
  await page.locator('#records').getByText('Revised animation contract', { exact: true }).waitFor();
  const searchResult = await downloadJSON('#download-records'); assert.equal(searchResult.data.length, 1); assert.equal(searchResult.filters.query, 'Revised animation');
  await page.locator('#kind').selectOption('procedural'); await page.locator('#list').click();
  await page.locator('#records').getByText('Verify artifacts', { exact: true }).waitFor();
  await page.locator('#records').getByRole('button', { name: '查看详情' }).click();
  await page.locator('#detail').getByText('Check the output file', { exact: true }).waitFor();
  await page.getByRole('tab', { name: '语义子图', exact: true }).click();
  await page.locator('#graph').click();
  await page.locator('#semantic-canvas [data-node-id="task"]').waitFor();
  await page.locator('#semantic-canvas [data-node-id="task"]').click();
  await page.locator('#node-detail').getByText('Reviewed new revision', { exact: true }).waitFor();
  assert.match(await page.locator('#semantic-results').innerText(), /produces/);
  await page.locator('#node-type').selectOption('artifact');
  assert.equal(await page.locator('#semantic-canvas [data-node-id]').count(), 1);
  const graph = await downloadJSON('#download-graph'); assert.equal(graph.data.nodes.length, 1); assert.equal(graph.data.nodes[0].id, 'file');
  await f.ok('put-memory', { sessionId, reason: 'Reviewed large node directory', record: { kind: 'semantic', visibility: 'private', summary: 'Large graph', content: { nodes: Array.from({ length: 61 }, (_, i) => ({ id: 'fact-'+i, type: 'fact', label: i===60?123:'Fact '+i })), edges: [] } } });
  await page.locator('#graph').click();
  await page.waitForFunction(() => document.querySelector('#feedback').textContent !== '处理中…');
  await page.locator('#node-type').selectOption('fact');
  assert.equal(await page.locator('#semantic-canvas [data-node-id]').count(), 60);
  await page.locator('#semantic-results tr').filter({ hasText: 'fact-60' }).getByRole('button', { name: '查看节点' }).click();
  await page.locator('#node-detail').getByRole('heading', { name: 'fact-60', exact: true }).waitFor();
  assert.equal((await downloadJSON('#download-graph')).data.nodes.length, 61);
  // Put the numeric-label node in the canvas too, where string slicing previously crashed.
  await f.ok('put-memory', { sessionId, reason: 'Reviewed numeric label', record: { kind: 'semantic', visibility: 'private', summary: 'Numeric label graph', content: { nodes: [{ id: 'numeric-label', type: 'numeric', label: 123 }], edges: [] } } });
  await page.locator('#graph').click(); await page.waitForFunction(() => document.querySelector('#feedback').textContent !== '处理中…');
  await page.locator('#node-type').selectOption('numeric'); await page.locator('#semantic-canvas [data-node-id="numeric-label"]').waitFor();
  await page.getByRole('tab', { name: '双时态审计', exact: true }).click();
  await page.locator('#audit-kind').selectOption('semantic');
  await page.locator('#system-at').fill(browserDate(first.systemTime));
  await page.locator('#audit-query').click();
  await page.locator('#audit-results').getByText('Animation contract', { exact: true }).waitFor();
  assert.match(await page.locator('#audit-results').innerText(), /v1/);
  assert.equal(await page.locator('#audit-results img').count(), 0);
  const snapshot = await downloadJSON('#download-audit'); assert.equal(snapshot.data.records[0].version, 1);
  assert.equal(snapshot.filters.systemAt, first.systemTime);
  await page.locator('#system-at').fill(''); await page.locator('#valid-at').fill('1970-01-01T00:00:01.501');
  await page.locator('#audit-query').click();
  await page.waitForFunction(() => document.querySelector('#feedback').textContent !== '处理中…');
  assert.equal((await downloadJSON('#download-audit')).data.records[0].version, 1);
  await page.locator('#audit-kind').selectOption('effects'); await page.locator('#audit-query').click();
  await page.locator('#audit-results').getByText(/普通记忆模式.*Effect/).waitFor();
  assert.equal((await downloadJSON('#download-audit')).data.nodes.length, 0);
  await page.screenshot({ path: join(f.root, 'structured-audit.png'), fullPage: true });
  const other = await f.ok('create-session', { workspaceRoot: f.workspace });
  await page.locator('#refresh').click(); await page.waitForFunction(() => document.querySelector('#feedback').textContent !== '处理中…');
  await page.locator('#sessions').selectOption(other.sessionId);
  await page.locator('#enabled').waitFor({ state: 'hidden' });
  assert.equal(await page.locator('#download-detail').isDisabled(), true, 'switching sessions must clear old downloadable data');
  assert.equal(await page.locator('#detail').innerText(), '选择记录查看详情。');
  assert.deepEqual(errors, []);
  assert.equal((await f.rpc('session.list', {})).items.every(item => !item.running), true);
  t.diagnostic(`Structured browser evidence retained: ${f.root}`);
});

async function fixture(t, options = {}) {
  const root = await mkdtemp(join(homedir(), 'dsh-memory-web-'));
  const workspace = join(root, 'workspace'); await mkdir(workspace);
  await options.seedNative?.(root, workspace);
  options.seed?.(join(root, 'memory/recovery.sqlite'), workspace);
  const probe = createServer(); await new Promise(r => probe.listen(0, '127.0.0.1', r));
  const port = probe.address().port; await new Promise(r => probe.close(r));
  const url = `http://127.0.0.1:${port}`;
  const child = spawn(process.execPath, [fileURLToPath(new URL('../src/cli.mjs', import.meta.url)), 'web', '--data-dir', root, '--workspace', workspace, '--port', String(port), '--no-open'], { env: { PATH: process.env.PATH, HOME: root }, stdio: ['ignore', 'pipe', 'pipe'] });
  let output = ''; child.stdout.on('data', b => output += b); child.stderr.on('data', b => output += b);
  const exit = new Promise(r => child.once('exit', (code, signal) => r({ code, signal })));
  t.after(async () => { if (child.exitCode === null && child.signalCode === null) child.kill('SIGTERM'); await exit; t.diagnostic(output.split('\n').filter(line => /SQLite|ExperimentalWarning/.test(line)).join('\n')); });
  const deadline = Date.now() + 30000;
  while (!output.includes(`dsh web: ${url}`)) { assert.equal(child.exitCode, null, output); assert.ok(Date.now() < deadline, output); await new Promise(r => setTimeout(r, 50)); }
  t.diagnostic(`Retained native Web: ${root}; ${url}`);
  const request = async (action, data = {}, headers = {}) => {
    const res = await fetch(`${url}/memory-recovery/api/${action}`, { method: 'POST', headers: { origin: url, 'content-type': 'application/json', ...headers }, body: JSON.stringify(data) });
    return { status: res.status, body: await res.json() };
  };
  const ok = async (action, data) => { const r = await request(action, data); assert.equal(r.status, 200, JSON.stringify(r)); return r.body.value; };
  const rpc = async (method, payload) => {
    const res = await fetch(`${url}/api/${method}`, { method: 'POST', headers: { origin: url, 'content-type': 'application/json' }, body: JSON.stringify({ type: 'client-request', rpcId: 'acceptance', method, payload }) });
    const body = await res.json(); assert.equal(body.result.ok, true, JSON.stringify(body)); return body.result.value;
  };
  return { root, workspace, url, request, ok, rpc };
}

test('real native Web creates an unstarted scoped session, versions records and pages without execution routes', { timeout: 60000 }, async t => {
  const f = await fixture(t);
  assert.equal((await fetch(`${f.url}/memory-recovery`)).status, 200);
  assert.deepEqual(await f.ok('defaults'), { workspaceRoot: f.workspace });
  const created = await f.ok('create-session', { workspaceRoot: f.workspace });
  const sessionId = created.sessionId;
  const config = { enabled: true, projectId: 'alpha', agentId: sessionId, workspaceRoot: f.workspace, sandbox: { sandbox_required: true, mode: 'workspace-write', network: 'host', workspaceRoot: f.workspace }, budgetTokens: 4000, anchors: [] };
  const configured = await f.ok('configure', { sessionId, input: config, expectedVersion: 0 });
  assert.equal(configured.executionCoverage, 'managed-sandbox-only');
  assert.equal((await f.request('configure', { sessionId, input: { ...config, sandbox: { ...config.sandbox, network: 'none' } }, expectedVersion: 1 })).body.code, 'SANDBOX_REQUIREMENT_UNSUPPORTED');
  assert.equal((await f.request('configure', { sessionId, input: { ...config, sandbox: null }, expectedVersion: 1 })).body.code, 'MEMORY_POLICY_DOWNGRADE_FORBIDDEN');
  assert.equal((await f.request('configure', { sessionId, input: config, expectedVersion: 0 })).body.code, 'MEMORY_CONFIG_VERSION_CONFLICT');
  const record = { kind: 'semantic', visibility: 'project', summary: 'alpha contract', validTime: 10, content: { nodes: [{ id: 'alpha', type: 'contract', label: 'Original' }, { id: 'beta', type: 'service' }], edges: [{ from: 'alpha', relation: 'uses', to: 'beta' }] } };
  const first = await f.ok('put-memory', { sessionId, record, reason: 'Reviewed contract' });
  assert.equal(first.sourceRefs[0].operatorId, 'local-operator');
  const listed = await f.ok('memories', { sessionId, filters: { kind: 'semantic' } });
  assert.equal(listed.length, 1);
  assert.equal(Object.hasOwn(listed[0], 'content'), false, 'list route must not transfer full record content');
  assert.equal(listed[0].id, first.id); assert.equal(listed[0].version, 1);
  assert.deepEqual(listed[0].sourceRefs, first.sourceRefs);
  assert.equal((await f.ok('memory', { sessionId, memoryId: first.id })).content.nodes[0].label, 'Original');
  assert.equal((await f.request('put-memory', { sessionId, record: { ...record, projectId: 'forged' }, reason: 'Spoof' })).status, 400);
  const second = await f.ok('put-memory', { sessionId, record: { ...record, id: first.id, expectedVersion: 1, validTime: 20, content: { ...record.content, nodes: [{ id: 'alpha', type: 'contract', label: 'Revised' }, record.content.nodes[1]] } }, reason: 'Reviewed revision' });
  assert.equal(second.version, 2);
  assert.equal((await f.ok('memory', { sessionId, memoryId: first.id, version: 1 })).content.nodes[0].label, 'Original');
  assert.equal((await f.ok('semantic-graph', { sessionId, filters: { validAt: 15 } })).nodes[0].label, 'Original');
  assert.equal((await f.ok('semantic-graph', { sessionId, filters: { systemAt: first.systemTime } })).records[0].version, 1);
  assert.equal((await f.ok('semantic-graph', { sessionId })).edges[0].relation, 'uses');
  const candidate = await f.ok('put-memory', { sessionId, record: { kind: 'procedural', visibility: 'private', status: 'candidate', content: { rules: ['Review before repeat'], applicability: {} }, summary: 'Review failure' }, reason: 'Operator observation' });
  assert.equal((await f.ok('confirm', { sessionId, memoryId: candidate.id, expectedVersion: 1, reason: 'Reviewed source' })).status, 'confirmed');
  assert.equal((await f.ok('memory', { sessionId, memoryId: candidate.id, version: 1 })).status, 'candidate');
  assert.equal((await f.request('confirm', { sessionId, memoryId: candidate.id, expectedVersion: 1, reason: 'Stale' })).body.code, 'MEMORY_VERSION_CONFLICT');
  assert.equal((await f.ok('memories', { sessionId, filters: { kind: 'episodic' } })).length > 0, true);
  const found = await f.ok('search', { sessionId, query: 'alpha' }); assert.equal(Object.hasOwn(found[0], 'content'), false);
  assert.match((await f.ok('page-in', { sessionId, memoryId: first.id, version: 1, maxChars: 1000 })).contentText, /Original/);
  assert.equal(await f.ok('page-out', { sessionId, memoryId: first.id }), true);
  assert.equal((await f.ok('memory', { sessionId, memoryId: first.id })).version, 2);
  const long = await f.ok('put-memory', { sessionId, reason: 'Reviewed tail pagination', record: { kind: 'semantic', visibility: 'private', summary: 'Long HTTP source',
    content: { nodes: [{ id: 'long', type: 'fact', text: 'x'.repeat(100100) + 'HTTP-TAIL-ONLY' }], edges: [] } } });
  const head = await f.ok('page-in', { sessionId, memoryId: long.id, maxChars: 100000 });
  const tail = await f.ok('page-in', { sessionId, memoryId: long.id, version: head.version, offset: head.nextOffset, maxChars: 1000 });
  assert.equal(tail.offset, 100000); assert.match(tail.contentText, /HTTP-TAIL-ONLY/);
  assert.equal(tail.hasMore, false); assert.equal(tail.nextOffset, null);
  assert.equal((await f.request('page-in', { sessionId, memoryId: long.id, version: 1, offset: -1 })).body.code, 'MEMORY_INVALID_OFFSET');
  const unicode = await f.ok('put-memory', { sessionId, reason: 'Reviewed Unicode source', record: { kind: 'semantic', visibility: 'private', summary: 'Unicode HTTP source',
    content: { nodes: [{ id: 'unicode', type: 'fact', text: 'A😀B' }], edges: [] } } });
  const unicodeText = JSON.stringify(unicode.content);
  const split = unicodeText.indexOf('😀') + 1;
  const unicodeHead = await f.ok('page-in', { sessionId, memoryId: unicode.id, version: 1, maxChars: split });
  const unicodeTail = await f.ok('page-in', { sessionId, memoryId: unicode.id, version: 1, offset: unicodeHead.nextOffset, maxChars: 1000 });
  assert.equal(unicodeHead.contentText + unicodeTail.contentText, unicodeText, 'real HTTP JSON must preserve both surrogate halves');
  assert.equal(unicodeHead.nextOffset, split); assert.equal(unicodeTail.nextOffset, null);
  const other = await f.ok('create-session', { workspaceRoot: f.workspace });
  await f.ok('configure', { sessionId: other.sessionId, input: { ...config, agentId: other.sessionId, projectId: 'beta', sandbox: null }, expectedVersion: 0 });
  assert.equal(await f.ok('memory', { sessionId: other.sessionId, memoryId: first.id }), null);
  const status = await f.ok('status', { sessionId }); assert.equal(status.pending, 0); assert.ok(status.durableThroughSeq >= 0);
  assert.deepEqual(await f.ok('effects', { sessionId }), []);
  for (const action of ['invokeTool', 'recover', 'projectContext', 'reconcile', 'execute']) assert.equal((await f.request(action, { sessionId, argv: ['true'], proof: { verified: true } })).status, 404);
  assert.equal((await f.request('sessions', {}, { origin: 'https://evil.example' })).status, 403);
  assert.equal((await f.request('sessions', {}, { 'sec-fetch-site': 'cross-site' })).status, 403);
  // Node fetch overwrites a supplied Host with the URL authority; use the actual HTTP wire.
  const wrongHost = await new Promise((resolve, reject) => {
    const req = httpRequest(`${f.url}/memory-recovery/api/sessions`, { method: 'POST', headers: { host: 'evil.example', origin: f.url, 'content-type': 'application/json' } }, res => { res.resume(); res.on('end', () => resolve(res.statusCode)); });
    req.on('error', reject); req.end('{}');
  });
  assert.equal(wrongHost, 403);
  assert.equal((await f.request('sessions', { actor: { role: 'operator' } })).status, 400);
  assert.equal((await fetch(`${f.url}/memory-recovery/api/sessions`)).status, 405);
  const noOrigin = await fetch(`${f.url}/memory-recovery/api/sessions`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' });
  assert.equal(noOrigin.status, 403);
  const badJson = await fetch(`${f.url}/memory-recovery/api/sessions`, { method: 'POST', headers: { origin: f.url, 'content-type': 'application/json' }, body: 'not-json' });
  assert.equal(badJson.status, 400); assert.doesNotMatch(await badJson.text(), /not-json/);
  assert.equal((await f.request('sessions', { padding: 'x'.repeat(262145) })).status, 413);
});

test('HTTP audit preserves UNKNOWN, causal edges and past system-time without recovering on reads', { timeout: 60000 }, async t => {
  let parent, stranded;
  const f = await fixture(t, { seed(path, workspaceRoot) {
    const store = new MemoryStore(path), effects = new EffectStore(store);
    const scope = { projectId: 'audit', sessionId: 'audit-new', agentId: 'audit-new' };
    const base = { ...scope, visibility: 'private', stepId: 'seed', toolName: 'memory_sandbox_run', input: {}, workspaceRoot, sandboxPolicy: {} };
    parent = effects.prepare({ ...base, callId: 'parent', validTime: 10 });
    stranded = effects.prepare({ ...base, callId: 'stranded', parentId: parent.id, causationId: parent.id, validTime: 10 });
    effects.begin(stranded.id, { id: 'former-process', scope }, { validTime: 20 }); store.close();
  } });
  await f.rpc('session.create', { sessionId: 'audit-new', cwd: f.workspace });
  await f.ok('configure', { sessionId: 'audit-new', expectedVersion: 0, input: { enabled: true, projectId: 'audit', agentId: 'audit-new', workspaceRoot: f.workspace, sandbox: null } });
  const graph = await f.ok('effect-graph', { sessionId: 'audit-new' });
  assert.equal(graph.nodes.find(n => n.id === stranded.id).state, 'UNKNOWN');
  assert.deepEqual(new Set(graph.edges.map(e => e.relation)), new Set(['parent', 'causation']));
  const before = await f.ok('effects', { sessionId: 'audit-new', filters: { systemAt: stranded.systemTime } });
  assert.equal(before.find(e => e.id === stranded.id).state, 'PREPARED');
  const valid = await f.ok('effects', { sessionId: 'audit-new', filters: { validAt: 15 } });
  assert.equal(valid.find(e => e.id === stranded.id).state, 'PREPARED');
  await f.ok('sessions');
  assert.deepEqual(await f.ok('effect-graph', { sessionId: 'audit-new' }), graph);
  const { chromium } = await import('playwright-core');
  const browser = await chromium.launchPersistentContext(join(f.root, 'effect-browser'), { headless: true, executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' });
  t.after(() => browser.close());
  const page = await browser.newPage();
  await page.goto(`${f.url}/memory-recovery?sessionId=audit-new`);
  await page.getByRole('tab', { name: '双时态审计', exact: true }).click();
  await page.locator('#audit-kind').selectOption('effects'); await page.locator('#audit-query').click();
  await page.locator('#audit-results').getByText('UNKNOWN · v3', { exact: true }).waitFor();
  assert.match(await page.locator('#audit-results').innerText(), /causation/);
  await page.locator('#system-at').fill(browserDate(stranded.systemTime));
  await page.locator('#audit-query').click();
  await page.waitForFunction(() => document.querySelector('#feedback').textContent !== '处理中…');
  assert.doesNotMatch(await page.locator('#audit-results').innerText(), /UNKNOWN/);
  assert.match(await page.locator('#audit-results').innerText(), /PREPARED · v1/);
  assert.deepEqual(await f.ok('effect-graph', { sessionId: 'audit-new' }), graph, 'browser audit must not mutate or replay effects');
});

test('independent browser creates/configures and actually opens its selected native chat', { timeout: 90000 }, async t => {
  const f = await fixture(t);
  const { chromium } = await import('playwright-core');
  // Persistent profile is deliberately retained; no browser cleanup deletes artifacts.
  const browser = await chromium.launchPersistentContext(join(f.root, 'browser-profile'), { headless: true, executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', viewport: { width: 1440, height: 1000 } });
  t.after(() => browser.close());
  const page = await browser.newPage();
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(`${f.url}/memory-recovery`);
  await page.waitForFunction(() => document.getElementById('feedback').textContent.includes('操作已完成'));
  assert.equal(await page.locator('#workspace').inputValue(), f.workspace);
  assert.equal(await page.locator('#project').inputValue(), '');
  assert.equal((await f.ok('sessions')).length, 0);
  assert.equal(await page.locator('#configure').isDisabled(), true);
  await page.locator('#project').fill('browser-project'); await page.locator('#workspace').fill(f.workspace);
  await page.locator('#mode').selectOption('read-only');
  await page.locator('#budget').fill('5200');
  await page.locator('#anchors').fill('Do not widen the file policy\nKeep the target contract');
  await page.getByRole('button', { name: '创建新原生会话', exact: true }).click();
  await page.locator('#open-chat').waitFor();
  const sessionId = await page.locator('#sessions').inputValue();
  assert.match(sessionId, /^session-/);
  assert.equal(await page.locator('#mode').inputValue(), 'read-only');
  assert.equal(await page.locator('#budget').inputValue(), '5200');
  assert.equal(await page.locator('#anchors').inputValue(), 'Do not widen the file policy\nKeep the target contract');
  const configureRequests = [];
  page.on('request', request => { if (request.url().endsWith('/api/configure')) configureRequests.push(request); });
  await page.locator('#project').fill('   ');
  await page.locator('#configure').click();
  await page.waitForFunction(() => document.getElementById('error').textContent.includes('请先填写显式项目 ID'));
  assert.equal(configureRequests.length, 0, 'missing project must not reach the server');
  await page.locator('#project').fill('browser-project');
  await page.locator('#budget').fill('127');
  await page.locator('#configure').click();
  await page.waitForFunction(() => document.getElementById('error').textContent.includes('128'));
  assert.equal(configureRequests.length, 0, 'invalid context budget must not reach the server');
  await page.locator('#budget').fill('5200');
  await page.getByRole('button', { name: '启用 / 保存新配置版本', exact: true }).click();
  await page.locator('#enabled').waitFor();
  assert.equal(await page.locator('#mode').inputValue(), 'read-only');
  const saved = await f.ok('config', { sessionId });
  assert.equal(saved.sandbox.mode, 'read-only'); assert.equal(saved.budgetTokens, 5200);
  assert.deepEqual(saved.anchors, ['Do not widen the file policy', 'Keep the target contract']);
  await page.locator('#manual-editor > summary').click();
  await page.locator('#summary').fill('Browser contract'); await page.locator('#reason').fill('Browser reviewed definition');
  await page.getByRole('button', { name: '追加记录版本', exact: true }).click();
  await page.waitForFunction(() => document.getElementById('version').value === '1');
  const memoryId = await page.locator('#memory-id').inputValue();
  assert.ok(memoryId);
  await page.getByText('工作集分页 / 调入与调出', { exact: true }).click();
  await page.locator('#max-chars').fill('20');
  await page.locator('#page-in').click();
  await page.locator('#detail dt').filter({ hasText: /^下一页偏移$/ }).waitFor();
  assert.equal(await page.locator('#detail dt').filter({ hasText: /^下一页偏移$/ }).evaluate(node => node.nextElementSibling.textContent), '20');
  await page.locator('#page-next').click();
  await page.waitForFunction(() => document.getElementById('page-offset').value === '20');
  assert.equal(await page.locator('#page-offset').inputValue(), '20');
  assert.equal(await page.locator('#version').inputValue(), '1');
  await page.screenshot({ path: join(f.root, 'memory-recovery.png'), fullPage: true });
  const nativeRequests = [];
  page.on('request', request => { if (request.url().includes('/api/')) { try { nativeRequests.push(request.postDataJSON()); } catch {} } });
  await page.locator('#open-chat').click();
  await page.getByRole('button', { name: '继续', exact: true }).click();
  await page.getByText('内测声明', { exact: true }).waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: '记忆：已启用', exact: true }).waitFor();
  await page.waitForTimeout(1000);
  assert.ok(nativeRequests.some(r => r?.payload?.sessionId === sessionId), JSON.stringify(nativeRequests));
  assert.equal((await f.rpc('session.list', {})).items[0].running, false);
  await page.screenshot({ path: join(f.root, 'native-selected-chat.png'), fullPage: true });
  assert.deepEqual(errors, []);
  t.diagnostic(`Native browser selected ${sessionId}; screenshots retained in ${f.root}`);
});

test('historical native session explains its boundary and keeps history while a new session enables memory', { timeout: 60000 }, async t => {
  const sessionId = 'history-config-regression';
  const f = await fixture(t, { async seedNative(root, workspace) {
    const require = createRequire(new URL('../../../third_party/deepseek-harness/apps/cli/package.json', import.meta.url));
    const { Context } = require('@deepseek-ai/cordis');
    const { default: Sessions } = await import('../../../third_party/deepseek-harness/packages/core/session/lib/index.js');
    const { default: Persistence } = await import('../../../third_party/deepseek-harness/packages/session/session-persistence-jsonl/lib/index.js');
    const ctx = new Context();
    try {
      await ctx.plugin(Sessions);
      await ctx.plugin(Persistence, { root: join(root, 'sessions'), compression: 'zstd', packChunks: false });
      const session = ctx.sessions.create(sessionId, { meta: { cwd: workspace } });
      session.append('turn/start', { turn: 1 });
      session.append('turn/end', { turn: 1, reason: { kind: 'completed' } });
      await ctx.sessions.flush(session);
    } finally { await ctx.fiber.dispose(); }
  } });
  assert.equal((await f.ok('sessions')).some(row => row.id === sessionId), false, 'history begins cold, not attached');
  assert.equal((await f.ok('config', { sessionId })).configurationBlockReason, 'MEMORY_NEW_SESSION_REQUIRED');
  const blocked = await f.request('configure', { sessionId, expectedVersion: 0, input: {} });
  assert.equal(blocked.body.code, 'MEMORY_NEW_SESSION_REQUIRED');
  assert.match(blocked.body.error, /创建新原生会话/);
  const { chromium } = await import('playwright-core');
  const browser = await chromium.launchPersistentContext(join(f.root, 'history-browser'), { headless: true, executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' });
  t.after(() => browser.close());
  const page = await browser.newPage();
  await page.goto(`${f.url}/memory-recovery`);
  await page.locator('#sessions').selectOption(sessionId);
  await page.waitForFunction(() => document.getElementById('configuration-notice').textContent.includes('此会话已有历史'));
  assert.equal(await page.locator('#configure').isDisabled(), true);
  assert.equal(await page.locator('#error').textContent(), '');
  await page.locator('#project').fill('history-followup');
  await page.locator('#mode').selectOption('memory-only');
  await page.locator('#create').click();
  await page.waitForFunction(() => !document.getElementById('configure').disabled);
  const newId = await page.locator('#sessions').inputValue();
  assert.notEqual(newId, sessionId);
  await page.locator('#configure').click();
  await page.locator('#enabled').waitFor();
  assert.equal((await f.ok('config', { sessionId: newId })).enabled, true);
  assert.equal((await f.ok('config', { sessionId })).version, 0);
  assert.equal((await f.ok('status', { sessionId })).durableThroughSeq, null);
  assert.ok((await f.rpc('session.list', {})).items.some(s => s.sessionId === sessionId && !s.running));
  await page.locator('#sessions').selectOption('');
  await page.waitForFunction(() => document.getElementById('config-version').textContent === '尚未选择会话');
  assert.equal(await page.locator('#configure').isDisabled(), true);
  assert.equal(await page.locator('#enabled').isVisible(), false);
  t.diagnostic('Real persisted native history preserved; new session configured through browser without model execution.');
});

test('restored unstarted native conversation enables memory without creating or running another session', { timeout: 60000 }, async t => {
  const sessionId = 'restored-blank-memory-regression';
  const f = await fixture(t, { async seedNative(root, workspace) {
    const require = createRequire(new URL('../../../third_party/deepseek-harness/apps/cli/package.json', import.meta.url));
    const { Context } = require('@deepseek-ai/cordis');
    const { default: Sessions } = await import('../../../third_party/deepseek-harness/packages/core/session/lib/index.js');
    const { default: Persistence } = await import('../../../third_party/deepseek-harness/packages/session/session-persistence-jsonl/lib/index.js');
    const ctx = new Context();
    try {
      await ctx.plugin(Sessions);
      await ctx.plugin(Persistence, { root: join(root, 'sessions'), compression: 'zstd', packChunks: false });
      const session = ctx.sessions.create(sessionId, { meta: { cwd: workspace } });
      session.append('permission/preset', { preset: 'workspace-write' });
      session.append('sandbox/mode', { mode: 'workspace-write' });
      session.append('approval/policy', { policy: 'ask' });
      await ctx.sessions.flush(session);
    } finally { await ctx.fiber.dispose(); }
  } });
  const before = (await f.rpc('session.list', {})).items.find(s => s.sessionId === sessionId);
  assert.equal(before.blank, true); assert.equal(before.running, false);
  assert.equal((await f.ok('config', { sessionId })).canConfigure, true, 'persisted policy-only session remains eligible after process restart');
  const { chromium } = await import('playwright-core');
  const browser = await chromium.launchPersistentContext(join(f.root, 'restored-blank-browser'), { headless: true, executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' });
  t.after(() => browser.close());
  await browser.addInitScript(id => { if (!localStorage.getItem('dsh.sessions.current')) localStorage.setItem('dsh.sessions.current', JSON.stringify({ sessionId: id })); }, sessionId);
  const page = await browser.newPage();
  await page.goto(f.url);
  await page.getByRole('button', { name: '继续', exact: true }).click();
  await page.getByText('内测声明', { exact: true }).waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: '记忆：未启用', exact: true }).click();
  await page.getByLabel('记忆项目 ID', { exact: true }).fill('abc');
  await page.getByRole('button', { name: '启用当前会话记忆', exact: true }).click();
  await page.getByRole('button', { name: '记忆：已启用', exact: true }).waitFor();
  const configured = await f.ok('config', { sessionId });
  assert.equal(configured.version, 1); assert.equal(configured.projectId, 'abc'); assert.equal(configured.sandbox, null);
  const after = await f.rpc('session.list', {});
  assert.equal(after.items.length, 1); assert.equal(after.items[0].blank, true); assert.equal(after.items[0].running, false);
  assert.equal(after.items[0].projections.values.sessionStats.turns, 0);
});

test('native composer enables ordinary memory for the selected session without imposing a sandbox', { timeout: 60000 }, async t => {
  const f = await fixture(t);
  const { sessionId } = await f.ok('create-session', { workspaceRoot: f.workspace });
  const { chromium } = await import('playwright-core');
  const browser = await chromium.launchPersistentContext(join(f.root, 'composer-browser'), { headless: true, executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', viewport: { width: 1440, height: 1000 } });
  t.after(() => browser.close());
  await browser.addInitScript(id => { if (!localStorage.getItem('dsh.sessions.current')) localStorage.setItem('dsh.sessions.current', JSON.stringify({ sessionId: id })); }, sessionId);
  const page = await browser.newPage(); const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(f.url);
  await page.getByRole('button', { name: '继续', exact: true }).click();
  await page.getByText('内测声明', { exact: true }).waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: '记忆：未启用', exact: true }).click({ timeout: 10000 });
  await page.emulateMedia({ colorScheme: 'dark' });
  const panel = page.locator('[data-memory-panel]');
  assert.equal(await panel.count(), 1);
  assert.equal(await page.getByLabel('工作目录', { exact: true }).evaluate(el => getComputedStyle(el).color), 'rgb(23, 48, 74)');
  await page.setViewportSize({ width: 390, height: 640 });
  const panelBox = await panel.boundingBox();
  assert.ok(panelBox.height <= 354, 'panel fits short viewport and scrolls');
  assert.equal(await panel.evaluate(el => getComputedStyle(el).overflowY), 'auto');
  await page.getByRole('button', { name: '刷新状态', exact: true }).click();
  await page.screenshot({ path: join(f.root, 'memory-panel-dark-narrow.png'), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByLabel('记忆项目 ID', { exact: true }).fill('composer-project');
  assert.equal(await page.getByLabel('独立强制沙箱').isChecked(), false);
  await page.getByRole('button', { name: '启用当前会话记忆', exact: true }).click();
  await page.waitForTimeout(300);
  assert.equal(await page.locator('[data-johnason-memory] [role="alert"]').allTextContents().then(items => items.join('')), '');
  await page.getByRole('button', { name: '记忆：已启用', exact: true }).waitFor();
  const config = await f.ok('config', { sessionId });
  assert.equal(config.projectId, 'composer-project'); assert.equal(config.sandbox, null);
  assert.equal(config.executionCoverage, 'native-memory-only');
  assert.equal((await f.rpc('session.list', {})).items.length, 1, 'configure binds existing composer, not another session');
  assert.equal((await f.rpc('session.list', {})).items[0].running, false);
  await page.reload();
  await page.getByRole('button', { name: '记忆：已启用', exact: true }).waitFor();
  assert.equal(await page.locator('svg[class*="_fish"], [class*="_fishHitbox"] svg').count(), 0, 'hero whale mark absent');
  await page.screenshot({ path: join(f.root, 'native-memory-composer.png'), fullPage: true });
  await page.getByRole('button', { name: '记忆：已启用', exact: true }).click();
  await page.getByLabel('常驻锚点', { exact: true }).fill('local unsaved draft');
  await f.ok('configure', { sessionId, expectedVersion: 1, input: {
    enabled: true, projectId: 'composer-project', agentId: sessionId, workspaceRoot: f.workspace,
    sandbox: null, budgetTokens: 3000, anchors: ['saved in other tab'],
  } });
  await page.evaluate(() => window.dispatchEvent(new Event('focus')));
  await page.getByRole('alert').filter({ hasText: '配置已在其他页面更新' }).waitFor();
  assert.equal(await page.getByRole('button', { name: '保存记忆配置', exact: true }).isDisabled(), true);
  assert.equal(await page.getByLabel('常驻锚点', { exact: true }).inputValue(), 'local unsaved draft');
  await page.getByRole('button', { name: '刷新状态', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('textarea[aria-label="常驻锚点"]').value === 'saved in other tab');
  assert.equal((await f.ok('config', { sessionId })).version, 2);
  const required = await f.ok('create-session', { workspaceRoot: f.workspace });
  await f.ok('configure', { sessionId: required.sessionId, expectedVersion: 0, input: {
    enabled: true, projectId: 'required-project', agentId: required.sessionId, workspaceRoot: f.workspace,
    budgetTokens: 2000, anchors: [], sandbox: { sandbox_required: true, mode: 'read-only', network: 'host', workspaceRoot: f.workspace },
  } });
  // The auxiliary link selects the actual native conversation, not a parallel UI session.
  await page.goto(`${f.url}/memory-recovery?sessionId=${required.sessionId}`);
  await page.locator('#open-chat').click();
  await page.getByRole('button', { name: '记忆：已启用', exact: true }).click();
  assert.equal(await page.getByLabel('记忆项目 ID', { exact: true }).inputValue(), 'required-project');
  assert.equal(await page.getByLabel('独立强制沙箱').isChecked(), true);
  assert.equal(await page.getByLabel('独立强制沙箱').isDisabled(), true);
  assert.equal(await page.getByLabel('沙箱模式').inputValue(), 'read-only');
  assert.equal(await page.getByLabel('沙箱模式').isDisabled(), true);
  await page.getByLabel('上下文预算', { exact: true }).fill('2200');
  await page.getByRole('button', { name: '保存记忆配置', exact: true }).click();
  await page.getByText('配置 v2', { exact: false }).waitFor();
  assert.equal((await f.ok('config', { sessionId: required.sessionId })).sandbox.mode, 'read-only');
  assert.equal((await f.ok('config', { sessionId })).version, 2, 'other session configuration unchanged');
  await page.getByRole('button', { name: '收起', exact: true }).click();
  await page.setViewportSize({ width: 800, height: 900 });
  const dock = await page.locator('[data-johnason-memory]').boundingBox();
  assert.ok(dock && dock.x >= 0 && dock.x + dock.width <= 801, 'dock remains inside narrow viewport');
  await page.screenshot({ path: join(f.root, 'native-memory-narrow.png'), fullPage: true });
  assert.deepEqual(errors, []);
  t.diagnostic(`Composer screenshot retained: ${join(f.root, 'native-memory-composer.png')}`);
});
